name: Jira Validation

on: [push]

jobs:
  find_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: developer-productivity/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    
      - name: Jira Find issue key
        uses: developer-productivity/gajira-find-issue-key@v2.0.1
        with:
          event: pull-request
          from: commits